name: Render-Book

on:
  push:
    branches:
      - main

jobs:
  bookdown:
    name: Build and Render Book
    runs-on: ubuntu-22.04

    steps:
      # Checkout repository
      - name: Checkout
        uses: actions/checkout@v4

      # Set up R + Pandoc
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2

      # Restore cache
      - name: Restore R package cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/R
          key: ${{ runner.os }}-r-packages-${{ hashFiles('DESCRIPTION') }}
          restore-keys: |
            ${{ runner.os }}-r-packages-

      # Install remotes
      - name: Install remotes
        run: |
          Rscript -e 'install.packages("remotes")'

      # Install dependencies from DESCRIPTION
      - name: Install dependencies
        run: |
          Rscript -e 'remotes::install_deps(dependencies = TRUE)'
          
       # Save cache
      - name: Save R package cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/R
          key: ${{ runner.os }}-r-packages-${{ hashFiles('DESCRIPTION') }}

      # Render book
      - name: Render book
        run: |
          Rscript -e 'bookdown::render_book("index.Rmd")'

      # Upload output artifact
      - name: Upload rendered book
        uses: actions/upload-artifact@v4
        with:
          name: _book
          path: _book/

  deploy:
    name: Deploy to GitHub Pages
    needs: bookdown
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: _book
          path: _book

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _book
          publish_branch: gh-pages

